language: php
php:
- 7.0
branches:
  only:
    - master
    - travis-ci

sudo: required

before_script:
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd /home/travis/build
- mkdir artifacts
- cd /home/travis/build/artifacts

script:
- curl -sL https://raw.githubusercontent.com/ImagicalCorp/php-build-scripts/master/plugswork.sh | bash
- cd plugins
- git clone https://github.com/MC-SG/OriginalSG
- cd OriginalSG
- rm -rf .git*
- cd ../..
- curl -sS https://raw.githubusercontent.com/MC-SG/OriginalSG/master/tests/TravisTest.php | php

# UPLOADING TO RELEASES WEBSITE
after_success:
- cd /home/travis/build
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- mv MC-SG remotevase
- git clone --branch=gh-pages https://github.com/MC-SG/OriginalSG
- cp /home/travis/build/artifacts/plugins/ImagicalDevTools//SurvivalGames_v0.0.2.phar /home/travis/build/OriginalSG/OriginalSG-$TRAVIS_JOB_ID.phar
- cp /home/travis/build/artifacts/plugins/ImagicalDevTools//SurvivalGames_v0.0.2.phar /home/travis/build/OriginalSG/service-download/SurvivalGames_v0.0.2.phar
- cd OriginalSG
- git add OriginalSG-$TRAVIS_JOB_ID.phar
- git add service-download/SurvivalGames_v0.0.2.phar
- chmod 777 _makeindex.sh
- ./_makeindex.sh
- echo >> list.txt
- echo "This is a directory listing of the root directory of the release download website. Copy the file name and paste it in the URL bar after deleting \"list.txt\". You can also alternatively download files using a shell script by downloading the file from http://MC-SG.github.io/OriginalSG/service-download/SurvivalGames_v0.0.2.phar" >> list.txt
- git commit -am "Added latest build"
- git push https://MC-SG:$GITHUB_API_KEY@github.com/MC-SG/OriginalSG gh-pages &>secret
#NOTE TO SELF: $GITHUB_API_KEY is set by going to https://travis-ci.org/MC-SG/REPONAME/settings
#Then, create an environment variable called "GITHUB_API_KEY" and hit create. The value field should be empty.
#Thats all! Google is very helpful sometimes

deploy:
  provider: releases
  user: ImagicalPhars
  password: SGPhars002
  file: "SurvivalGames*.phar"
  skip_cleanup: true
  on:
    tags: true

#env:
 #global:
  #- REPO_OWNER="MC-SG"
  #- REPO_NAME="OriginalSG"
  #- PUSH_REPO_OWNER="remotevase"
  #- PUSH_REPO_NAME="OriginalSG"
  #- PUSH_REPO_USER="remotevase"
  #- PUSH_REPO_EUSER="web.articlerequests@gmail.com"
  #- PUSH_REPO_BRANCH="master"
  #- COMMIT_MESSAGE="Add latest commits!"
  #- DATATP="phar"
  #- DOWNLOAD_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/$REPO_NAME-$TRAVIS_JOB_ID.$DATATP" 
  #- DIRECT_DL_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/service-download/$REPO_NAME.$DATATP"
