language: php
php:
- 7.0
branches:
  only:
    - master
    - travis-ci

sudo: required

before_script:
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd /home/travis/build
- mkdir artifacts
- cd /home/travis/build/artifacts

script:
- curl -sL https://raw.githubusercontent.com/ImagicalCorp/php-build-scripts/master/plugswork.sh | bash
- cd plugins
- git clone https://github.com/$REPO_OWNER/$REPO_NAME
- cd $REPO_NAME
- rm -rf .git*
- cd ../..


#deploy:
  #provider: releases
  #api_key: "22d0d75cc4e492e341dd42d89a8793d31acb5085"
  #file: "SurvivalGames*.phar"
  #skip_cleanup: true
  #on:
    #tags: false
    #allbranches: true

env:
 global:
  - REPO_OWNER="MC-SG"
  - REPO_NAME="OriginalSG"
  - PUSH_REPO_OWNER="remotevase"
  - PUSH_REPO_NAME="OriginalSG"
  - PUSH_REPO_USER="remotevase"
  - PUSH_REPO_EUSER="web.articlerequests@gmail.com"
  - PUSH_REPO_BRANCH="master"
  - COMMIT_MESSAGE="Add latest commits!"
  - DATATP="phar"
  - DOWNLOAD_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/$REPO_NAME-$TRAVIS_JOB_ID.$DATATP" 
  - DIRECT_DL_URI="http://$PUSH_REPO_OWNER/$PUSH_REPO_NAME/service-download/$REPO_NAME.$DATATP"
